name: Testing workflows

on: 
    push: 
        branches: 
            - main

jobs:
    First-command:
        name: Testing commands
        runs-on: [ubuntu-latest]
        steps:
            - name: Checking out repo
              uses: actions/checkout@v4

            - name: First command
              run: "echo FIRST COMMAND"

    Second-command:
        needs: First-command
        name: Final testing
        runs-on: [windows-latest]
        steps:
            - name: Last command
              run: "echo LAST COMMAND"
    

        
        
