name: Push workflows

on:
    push:
        branches:
            - main

jobs:
    Type-checking:
        name: Type-checking🧐
        runs-on: [ubuntu-latest]

        steps:
            - name: Setup Bun
              uses: oven-sh/setup-bun@v2.0.1

            - name: Checking out repo
              uses: actions/checkout@v4

            - name: Setup deps
              run: bun i

            - name: Type check
              run: bun run typecheck

    Vitest:
        name: Vitest unit-tests⚡
        runs-on: [ubuntu-latest]

        steps:
          - name: Setup Bun
            uses: oven-sh/setup-bun@v2.0.1

          - name: Checkout repo
            uses: actions/checkout@v4

          - name: Setup env variables
            run: touch .env | cp .env.example .env

          - name: Install dependancies
            run: bun i

          - name: Run unit tests
            run: bun run test

