name: Test workflows
on: [push]
run-name: Tesing env vars
jobs:
  test-workflows:
    environment: Production
    runs-on: ubuntu-latest
    steps:
       - run: "echo ${{vars.RUN_TESTS}}"
       - name: "attempt test"
       - if: vars.RUN_TESTS == TRUE
